# based on linuxkit/examples/docker.yml
kernel:
  image: linuxkit/kernel:4.19.27
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:005807f5c6a74e23f485a6d1657818bdccb70cd0
  - linuxkit/runc:606971451ea29b4238029804ca638f9f85caf5af
  - linuxkit/containerd:6e6841be5ad15c30752d81d121b247fa3ae08c97
  - linuxkit/ca-certificates:906c46a26fd2df271bf64c0259bf2267f7593213
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: mount
    image: linuxkit/swap:v0.6
    command: ["/sbin/swapon", "LABEL=swap"]
  - name: format
    image: linuxkit/format:v0.6
  - name: mount
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib/docker"]
  - name: metadata
    image: linuxkit/metadata:566864a2e22e318c478ab284f5675da7a7a12f38
    command: ["/usr/bin/metadata", "cdrom"]
services:
  - name: getty
    image: linuxkit/getty:01993189b8c583dc91cbbc7d4be131832c0fc205
    env:
     - INSECURE=true
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: ntpd
    image: linuxkit/openntpd:v0.6
  - name: docker
    image: docker:18.09-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /run/config/docker:/var/config/docker
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd", "--",
        "--config-file", "/var/config/docker/daemon.json",
        "--host", "tcp://0.0.0.0:2375", "--storage-driver", "overlay2"]
    runtime:
      mkdir: ["/var/lib/docker"]
trust:
  org:
    - linuxkit
    - library
