# based on linuxkit/examples/docker.yml
kernel:
  image: linuxkit/kernel:4.19.20
  cmdline: "console=ttyAMA0"
init:
  - linuxkit/init:a2166a6048ce041eebe005ab99454cfdeaa5c848
  - linuxkit/runc:069d5cd3cc4f0aec70e4af53aed5d27a21c79c35
  - linuxkit/containerd:2aff4d486220667364b2971b5fc6225bf165a069
  - linuxkit/ca-certificates:v0.6
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.6
  - name: sysfs
    image: linuxkit/sysfs:v0.6
  - name: format
    image: linuxkit/format:v0.6
  - name: mount
    image: linuxkit/mount:v0.6
    command: ["/usr/bin/mountie", "/var/lib/docker"]
  - name: swap
    image: linuxkit/swap:v0.6
    command: ["/swap.sh", "--path", "/var/lib/swap", "--size", "1024M"]
services:
  - name: acpid
    image: linuxkit/acpid:v0.6
  - name: getty
    image: linuxkit/getty:2eb742cd7a68e14cf50577c02f30147bc406e478
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.6
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.6
  - name: ntpd
    image: linuxkit/openntpd:v0.6
  - name: docker
    image: docker:18.06.0-ce-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd", "--",
        "-H", "tcp://0.0.0.0:2375",
        "--config-file", "/var/config/docker/daemon.json",
        "--storage-driver", "overlay2" ]
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
trust:
  org:
    - linuxkit
    - library
