version: 2.1

jobs:
  build:
    docker:
      # docker client (on native host)
      - image: linuxkitrpi/circleci-builder
      # docker daemon (on arm64)
      - image: linuxkitrpi/dockerd-arm64
    steps:
      - checkout
      - restore_cache:
          keys:
            - run-if-changed-{{ .Branch }}
            - run-if-changed
      - run:
          name: Wait for dockerd-arm64 to come up
          command: wait-for-dockerd
      - run:
          name: Build tools/linuxkit-cli
          shell: run-if-changed -e CIRCLE_BRANCH -e DOCKER_LOGIN -e DOCKER_PASSWORD -d tools/linuxkit-cli
          command: |
            cd tools/linuxkit-cli
            docker build -t linuxkitrpi/linuxkit-cli .
            if [ "$CIRCLE_BRANCH" = "master" ] ; then
              docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"
              docker push linuxkitrpi/linuxkit-cli
            fi
          no_output_timeout: 30m
      - save_cache:
          key: run-if-changed-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - ".cache/run-if-changed"