version: 2.1

jobs:
  build:
    docker:
      - image: linuxkitrpi/linuxkit-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build (cross-compile) and push pkg/kernel
          command: |
            # cross compile kernel
            IMAGE=$(linuxkit pkg show-tag pkg/kernel)
            docker build -t "${IMAGE}-arm64" --build-arg "AARCH64_CROSS_COMPILE=1" pkg/kernel
            # hack manifest arch from amd64 to arm64
            LAYERS=$(mktemp -d "${TMPDIR:-/tmp}/layers.XXXXXXXXX")
            docker save "${IMAGE}-arm64" | tar -C "$LAYERS" -x
            find "$LAYERS" -type f \( -name 'json' -o -name '*.json' \) \
                -exec sed -i 's|\("architecture"\s*:\s*\)"amd64"|\1"arm64"|g' '{}' \;
            tar -C "$LAYERS" -c . | docker load
            # push manifest and image
            if [ "$CIRCLE_BRANCH" = "master" ] ; then
              docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
              linuxkit pkg push -disable-content-trust pkg/kernel
            fi