version: 2.1

executors:
  builder_arm64:
    docker:
      - image: linuxkitrpi/linuxkit-cli:54ffd7bd1c1d42a9aa0027474720aa2360c45b11
        environment:
          DOCKER_HOST: tcp://localhost:2375
      - image: linuxkitrpi/dockerd-arm64:055c8da09206ccc107a12ccd2d095507ae1f8c59
  builder_amd64:
    docker:
      - image: linuxkitrpi/linuxkit-cli:54ffd7bd1c1d42a9aa0027474720aa2360c45b11

jobs:
  build_arm64:
    executor: builder_arm64
    steps:
      - checkout
      - run:
          name: Build Packages on ARM64
          command: |
            ./build.sh -s \
              images/dockerd.yml \
              pkg/chrony \
              pkg/firmware \
              pkg/wireless-regdb \
              pkg/wpa_supplicant \
              tools/linuxkit-cli \
              tools/mkimage-rpi3-squashfs
          no_output_timeout: 20m
      - persist_to_workspace:
          root: build
          paths:
            - "*.tar"
  build_amd64:
    executor: builder_amd64
    steps:
      - checkout
      - setup_remote_docker:
          version: "18.09.3"
      - run:
          name: Build Packages on AMD64
          command: |
            ./build.sh -s \
              kernel \
              pkg/chrony \
              pkg/wireless-regdb \
              pkg/wpa_supplicant \ \
              tools/dockerd-arm64 \
              tools/linuxkit-cli \
              tools/mkimage-rpi3-squashfs
          no_output_timeout: 20m
      - persist_to_workspace:
          root: build
          paths:
            - "*.tar"
  push:
    executor: builder_amd64
    steps:
      - checkout
      - attach_workspace:
          at: build
      - setup_remote_docker:
          version: "18.09.3"
      - run:
          name: Restore Images from Workspace
          command: find build/ -type f -name '*.tar' -exec docker load -i '{}' \;
      - run:
          name: Log in to Docker
          command: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - run:
          name: Push Images to Docker Hub
          command: |
            ./build.sh -p \
              kernel \
              images/dockerd.yml \
              pkg/chrony \
              pkg/firmware \
              pkg/wireless-regdb \
              pkg/wpa_supplicant \
              tools/dockerd-arm64 \
              tools/linuxkit-cli \
              tools/mkimage-rpi3-squashfs

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_amd64
      - build_arm64
      - push:
          context: dockerhub-creds
          requires:
            - build_amd64
            - build_arm64
          filters:
            branches:
              only: master