version: 2.1

jobs:
  build:
    docker:
      - image: linuxkitrpi/linuxkit-cli
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build (cross-compile) and push pkg/kernel
          command: |
            IMAGE=$(linuxkit pkg show-tag pkg/kernel)
            LAYERS=$(mktemp -d "${TMPDIR:-/tmp}/layers.XXXXXXXXX")
            # cross compile kernel
            docker build -t "${IMAGE}-arm64" --build-arg "AARCH64_CROSS_COMPILE=1" pkg/kernel
            # change manifest arch from amd64 to arm64
            docker save "${IMAGE_REPOSITORY}:${IMAGE_TAG}" | tar -C "$LAYERS" -x
            find "$LAYERS" -type f \( -name 'json' -o -name '*.json' \) \
                -exec sed -i 's|\("architecture"\s*:\s*\)"amd64"|\1"arm64"|g' '{}' \;
            tar -C "$LAYERS" -c . | docker load
            # push manifest and image
            if [ "$CIRCLE_BRANCH" = "master" ] ; then
              docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
              linuxkit pkg push pkg/kernel
            fi

  old_build:
    docker:
      # docker client (on native host)
      - image: linuxkitrpi/circleci-builder
      # docker daemon (on arm64)
      - image: linuxkitrpi/dockerd-arm64
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-docker-layer-cache
      - run:
          name: Wait for dockerd-arm64 to come up
          command: wait-for-dockerd
      - run:
          name: Restore Docker images
          command: |
            if [ -f /tmp/images.tar ] ; then
              docker load -i /tmp/images.tar
            fi
      - run:
          name: Build tools/linuxkit-cli
          command: |
            cd tools/linuxkit-cli
            docker build -t linuxkitrpi/linuxkit-cli .
            if [ "$CIRCLE_BRANCH" = "master" ] ; then
              docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
              docker push linuxkitrpi/linuxkit-cli
            fi
          no_output_timeout: 30m
      - run:
          command: |
            docker run --name linuxkit-cli \
              -e CIRCLE_BRANCH -e DOCKER_HOST -e DOCKER_LOGIN -e DOCKER_PASSWORD \
              --network host -v /workspace -w /workspace -t -i -d \
              linuxkitrpi/linuxkit-cli cat

            docker cp -a . linuxkit-cli:/workspace
            for pkg in pkg/*/ ; do
                echo "Building $pkg"
                docker exec -e PKG="$pkg" -t -i linuxkit-cli /bin/sh -eu -c '
                  linuxkit pkg build -disable-content-trust "$PKG"
                  if [ "$CIRCLE_BRANCH" = "master" ] ; then
                    docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
                    linuxkit pkg push -disable-content-trust "$PKG"
                  fi
                '
            done
          no_output_timeout: 60m
      - run: docker save -o /tmp/images.tar $(docker images -q | xargs -n 1 docker history -q | grep -v '<missing>')
      - save_cache:
          key: v1-docker-layer-cache-{{ .BuildNum }}
          paths:
            - /tmp/images.tar