version: 2.1

jobs:
  build_arm64:
    docker:
      - image: linuxkitrpi/linuxkit-cli:54ffd7bd1c1d42a9aa0027474720aa2360c45b11
        environment:
          DOCKER_HOST: tcp://localhost:2375
      - image: linuxkitrpi/dockerd-arm64:055c8da09206ccc107a12ccd2d095507ae1f8c59
    steps:
      - checkout
      - run:
          name: Build 
          command: |
            sh -x build.sh -s \
              pkg/* \
              tools/linuxkit-cli \
              tools/mkimage-rpi3-squashfs \
              images/dockerd.yml
          no_output_timeout: 20m
      - persist_to_workspace:
          root: build
          paths:
            - '*.tar'
  build_amd64:
    docker:
      - image: linuxkitrpi/linuxkit-cli:54ffd7bd1c1d42a9aa0027474720aa2360c45b11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build 
          command: |
            sh -x build.sh -s \
              pkg/* \
              tools/linuxkit-cli \
              tools/mkimage-rpi3-squashfs \
              images/dockerd.yml
          no_output_timeout: 20m
      - persist_to_workspace:
          root: build
          paths:
            - '*.tar'
  push:
    docker:
      - image: linuxkitrpi/linuxkit-cli:54ffd7bd1c1d42a9aa0027474720aa2360c45b11
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: build
      - run:
          name: Restore Images from Workspace
          command: find build/ -type f -name '*.tar' -exec docker load -i '{}' \;
      - run:
          name: Log in to Docker
          command: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - run:
          name: Push Images to Docker Hub
          command: |
            sh -x build.sh -p pkg/* tools/* kernel images/dockerd.yml

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_amd64
      - build_arm64
      - push:
          context: dockerhub-creds
          requires:
            - build_amd64
            - build_arm64
          filters:
            branches:
              only: master