version: 2.1

orbs:
  builder: linuxkitrpi/builder@0.1.2

jobs:
  build_arm64:
    executor: builder/arm64
    steps:
      - checkout
      - builder/wait_for_docker
      - run:
          name: Build Packages on ARM64
          command: |
            mkdir -p build
            ./build.sh -s build -w . \
              images/dockerd.yml \
              pkg/chrony \
              pkg/firmware \
              pkg/wireless-regdb \
              pkg/wpa_supplicant \
              tools/builder \
              tools/linuxkit-cli \
              tools/mkimage-rpi3-squashfs
          no_output_timeout: 20m
      - persist_to_workspace:
          root: .
          paths: build
  build_amd64:
    executor: builder/amd64
    steps:
      - checkout
      - setup_remote_docker:
          version: "18.09.3"
      - run:
          name: Build Packages on AMD64
          command: |
            mkdir -p build
            ./build.sh -s build -w . \
              kernel \
              pkg/chrony \
              pkg/wireless-regdb \
              pkg/wpa_supplicant \
              tools/builder \
              tools/dockerd-arm64 \
              tools/linuxkit-cli \
              tools/mkimage-rpi3-squashfs
          no_output_timeout: 20m
      - persist_to_workspace:
          root: .
          paths: build
  push:
    executor: builder/amd64
    steps:
      - checkout
      - attach_workspace:
          at: /run/images
      - setup_remote_docker:
          version: "18.09.3"
      - run:
          name: Restore Images from Workspace
          command: find /run/images -type f -name '*.tar' -exec docker load -i '{}' \;
      - run:
          name: Log in to Docker
          command: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - run:
          name: Push Images to Docker Hub
          command: |
            ./build.sh -Bp -w . \
              kernel \
              images/dockerd.yml \
              pkg/chrony \
              pkg/firmware \
              pkg/wireless-regdb \
              pkg/wpa_supplicant \
              tools/builder \
              tools/dockerd-arm64 \
              tools/linuxkit-cli \
              tools/mkimage-rpi3-squashfs

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_amd64
      - build_arm64
      - push:
          context: dockerhub-creds
          requires:
            - build_amd64
            - build_arm64
          filters:
            branches:
              only: master