version: 2.1

commands:
  wait_for_docker:
    steps:
      - run:
          name: Wait for dockerd to come up
          command: |
            DOCKER_API="http://${DOCKER_HOST}/v1.39/info"
            until wget -q --spider "$DOCKER_API" 2>/dev/null ; do
              sleep 1
            done
  save_docker_cache:
    parameters:
      build_log:
        type: string
        default: "build.log"
      key:
        type: string
    steps:
      - run:
          name: Save Layers to Cache
          command: |
            IMAGES=""
            for i in $(sed -n 's/^ ---> \([[:xdigit:]]\+\)$/\1/p' << parameters.build_log >>) ; do
              if [ "$(docker inspect --format '{{.Size}}' "$i")" -gt 0 ] ; then
                IMAGES="$IMAGES $i"
              fi
            done

            mkdir -p /var/cache/layers
            docker save -o "/var/cache/layers/build.tar" $IMAGES
      - save_cache:
          key: << parameters.key >>
          paths:
            - /var/cache/layers
  restore_docker_cache:
    parameters:
      key:
        type: string
    steps:
      - restore_cache:
          keys:
            - << parameters.key >>
      - run:
          name: Restore Layers from Cache
          command: docker load -i /var/cache/layers/build.tar || true

jobs:
  build_cli_arm64:
    docker:
      - image: linuxkitrpi/linuxkit-cli
        environment:
          DOCKER_HOST: localhost:2375
      - image: linuxkitrpi/dockerd-arm64
    steps:
      - checkout
      - wait_for_docker
      - restore_docker_cache:
          key: v1-images-cli-arm64
      - run:
          name: Build tools/linuxkit-cli
          command: |
            TAG="linuxkitrpi/linuxkit-cli:$(date "+%Y%m%d")-arm64"
            # build linuxkit-cli image
            cd tools/linuxkit-cli
            docker build -t "$TAG" . | tee -a build.log
            # save for push stage
            mkdir -p /run/images
            docker save -o /run/images/linuxkit-cli-arm64.tar "$TAG"
          no_output_timeout: 30m
      - persist_to_workspace:
          root: /run/images
          paths:
            - linuxkit-cli-arm64.tar
      - save_docker_cache:
          key: v1-images-cli-arm64-{{ .BuildNum }}
  build_pkgs:
    docker:
      - image: linuxkitrpi/linuxkit-cli
        environment:
          DOCKER_HOST: localhost:2375
      - image: linuxkitrpi/dockerd-arm64
    steps:
      - checkout
      - wait_for_docker
      - restore_docker_cache:
          key: v1-images-pkg
      - run:
          command: |
            # packages to build on arm64
            PKGS="chrony firmware wireless-regdb wpa_supplicant"
            # spawn a background container for running the linuxkit-cli on arm64
            docker run -t -i -d -e DOCKER_HOST -v /workspace -w /workspace \
              --network host --name linuxkit-cli linuxkitrpi/linuxkit-cli cat
            docker cp -a . linuxkit-cli:/workspace
            # build each package separately
            for pkg in $PKGS; do
              docker exec -t linuxkit-cli linuxkit pkg build -disable-content-trust "$pkg" | tee -a build.log
            done
          no_output_timeout: 30m
      - save_docker_cache:
          key: v1-images-pkg-{{ .BuildNum }}

  build_kernel:
    docker:
      - image: linuxkitrpi/linuxkit-cli
    steps:
      - checkout
      - setup_remote_docker
      - restore_docker_cache:
          key: v1-images-kernel
      - run:
          name: Cross-Compile RaspberryPi Kernel
          command: |
            TAG="$(linuxkit pkg show-tag pkg/kernel)-arm64"
            # cross compile kernel
            docker build -t "$TAG" --build-arg "AARCH64_CROSS_COMPILE=1" pkg/kernel | tee -a build.log
            # fix manifest architecture
            LAYERS=$(mktemp -d "${TMPDIR:-/tmp}/layers.XXXXXXXXX")
            docker save "$TAG" | tar -C "$LAYERS" -x
            find "$LAYERS" -type f \( -name 'json' -o -name '*.json' \) \
                -exec sed -i 's|\("architecture"\s*:\s*\)"amd64"|\1"arm64"|g' '{}' \;
            tar -C "$LAYERS" -c . | docker load
            # save for push stage
            mkdir -p /run/images
            docker save -o /run/images/kernel.tar "${TAG}"
      - persist_to_workspace:
          root: /run/images
          paths:
            - kernel.tar
      - save_docker_cache:
          key: v1-images-kernel-{{ .BuildNum }}
  push:
    docker:
      - image: linuxkitrpi/linuxkit-cli
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /run/images
      - run:
          name: Restore Images from Workspace
          command: find /run/images -type f -name '*.tar' -exec docker load -i '{}' \;
      - run:
          name: Log in to Docker
          command: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - run:
          name: Pushing Images
          command: |
            # push all locally available images
            TAGS=$(docker images --filter 'reference=linuxkitrpi/*' --format '{{.Repository}}:{{.Tag}}')
            for tag in $TAGS ; do
              docker push "$tag"
            done
            # push multiarch manifests
            TARGETS=$(printf '%s' "$TAGS" | sed -n -r 's/(.*)-(amd64|arm64)/\1/p')
            for target in $TARGETS ; do
              push-manifest.sh "$target"
            done

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_cli_arm64
      - build_kernel
      - build_pkgs
      - push:
          requires:
            - build_kernel
            - build_pkgs