version: 2.1

jobs:
  build:
    docker:
      # docker and git client (on native host)
      - image: circleci/buildpack-deps:bionic-scm
        environment:
          - DOCKER_HOST: localhost:2375
      # docker daemon (on arm64)
      - image: linuxkitrpi/dockerd-arm64
    steps:
      - restore_cache:
          keys:
            - cached-runs
      - checkout
      - run: scripts/prepare-circleci-env
      - run:
          name: Build tools/linuxkit-cli
          shell: run-if-changed -d tools/linuxkit-cli
          command: |
            cd tools/linuxkit-cli
            docker build -t linuxkitrpi/linuxkit-cli .
          no_output_timeout: 30m
      - run:
          name: Log in to Docker Hub
          command: docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"
      - run:
          name: Push tools/linuxkit-cli
          shell: run-if-changed -d tools/linuxkit-cli
          command: |
            cd tools/linuxkit-cli
            docker push linuxkitrpi/linuxkit-cli
      - save_cache:
          key: cached-runs
          paths:
            - ".cache"