version: 2.1

jobs:
  build:
    docker:
      # docker client (on native host)
      - image: linuxkitrpi/circleci-builder
      # docker daemon (on arm64)
      - image: linuxkitrpi/dockerd-arm64
    steps:
      - checkout
      - restore_cache:
          keys:
            - run-if-changed-{{ .Branch }}
            - run-if-changed
      - run:
          name: Wait for dockerd-arm64 to come up
          command: wait-for-dockerd
      - run:
          name: Build and push tools/linuxkit-cli
          shell: run-if-changed -d tools/linuxkit-cli
          command: |
            cd tools/linuxkit-cli
            docker build -t linuxkitrpi/linuxkit-cli .
            if [ "$CIRCLE_BRANCH" = "master" ] ; then
              docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
              docker push linuxkitrpi/linuxkit-cli
            fi
          no_output_timeout: 30m
      - run:
          command: |
            docker run --name linuxkit-cli \
              -e CIRCLE_BRANCH -e DOCKER_HOST -e DOCKER_LOGIN -e DOCKER_PASSWORD \
              -v /workspace -w /workspace -t -i -d \
              linuxkitrpi/linuxkit-cli cat

            docker cp -a . linuxkit-cli:/workspace
            for pkg in pkg/*/ ; do
                echo "Building $pkg"
                run-if-changed -d "$pkg" -- docker exec -e PKG="$pkg" -t -i linuxkit-cli /bin/sh -eu -c '
                  linuxkit pkg build -disable-content-trust "$PKG"
                  if [ "$CIRCLE_BRANCH" = "master" ] ; then
                    docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
                    linuxkit pkg push -disable-content-trust "$PKG"
                  fi
                '
            done
      - save_cache:
          key: run-if-changed-{{ .Branch }}-{{ .BuildNum }}
          paths:
            - ".cache/run-if-changed"
