# based on linuxkit/examples/docker.yml
kernel:
  image: linuxkit/kernel:4.19.27
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:v0.7
  - linuxkit/runc:v0.7
  - linuxkit/containerd:v0.7
  - linuxkit/ca-certificates:v0.7
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.7
  - name: sysfs
    image: linuxkit/sysfs:v0.7
  - name: mount
    image: linuxkit/swap:v0.7
    command: ["/sbin/swapon", "LABEL=swap"]
  - name: mount
    image: linuxkit/mount:v0.7
    command: ["/usr/bin/mountie", "-label", "dockerconf", "/var/config/docker"]
  - name: format
    image: linuxkit/format:v0.7
  - name: mount
    image: linuxkit/mount:v0.7
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:01993189b8c583dc91cbbc7d4be131832c0fc205
    env:
     - INSECURE=true
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.7
  - name: ntpd
    image: linuxkit/openntpd:v0.7
  - name: docker
    image: docker:18.09-dind
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /var/config/docker:/var/config/docker
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd", "--",
        "--config-file", "/var/config/docker/daemon.json",
        "--host", "tcp://0.0.0.0:2375", "--storage-driver", "overlay2"]
    runtime:
      mkdir:
        - /var/lib/docker
trust:
  org:
    - linuxkit
    - library
