#!/bin/sh
# This script assumes to be running inside the following container:
#
#  image: circleci/buildpack-deps:bionic-scm
#  environment:
#    - DOCKER_HOST: localhost:2375
set -eu

echo "Install helper scripts for global use"
SCRIPTS_SRC=$(dirname "$0")
sudo cp "/usr/local/bin/run-if-changed" "${SCRIPTS_DST}"

echo "Wait for dockerd-arm64 to come up"
dockerize -wait "http://${DOCKER_HOST}/v1.39/info" -timeout 5m
