#!/bin/sh
# This script assumes to be running inside the following container:
#
#  image: circleci/buildpack-deps:bionic-scm
#  environment:
#    - DOCKER_HOST: localhost:2375
set -eu

echo "Install helper scripts for global use"
sudo cp "$(dirname "$0")/run-if-changed" "/usr/local/bin/"

echo "Wait for dockerd-arm64 to come up"
dockerize -wait "http://${DOCKER_HOST}/v1.39/info" -timeout 5m
