image: chrony
org: linuxkitrpi
network: true
config:
  binds:
   - /etc/resolv.conf:/etc/resolv.conf
   - /var/lib/chrony:/var/lib/chrony
  runtime:
    mkdir: ["/var/lib/chrony"]
  capabilities:
   - CAP_SYS_TIME
   - CAP_CHOWN
   - CAP_SETUID
   - CAP_SETGID
